### ISSUE TITLE
Create box ''filmreklam'' for every page

### ISSUE THREAD

**Issue by MikaelaMathisson** [sebastianpiresmolin/cinema#1]
Create box with image or video (iframe for example) for movie advertising.
Add Title

**_User Story:
As a user i want to see some advertising for the upcoming movies on the website._**

**Comment by MikaelaMathisson** [comment]
Pull request finns här:
 https://github.com/sebastianpiresmolin/cinema/pull/5

Vet att jag jobbat tidigare här under helgen innan jul men det är för att jag ska jobba i Norge under mellandagarna. :) Pinga mig gärna om det är något knas

**Comment by MikaelaMathisson** [comment]
@sebastianpiresmolin  Du får gärna testa den här. Har lagt till det du sa och mergat

**Comment by rasmusbaeckstrom** [comment]
@MikaelaMathisson It looks good but shouldn't there be advertising on movies.html as well?

**Comment by MikaelaMathisson** [comment]
@rasmusbaeckstrom I have added that now :) If the rest looks good, please add it to done
