### ISSUE TITLE
Create  mobile Dropdown menu on ABOUT.html

### ISSUE THREAD

**Issue by MikaelaMathisson** [sebastianpiresmolin/cinema#2]
Create dropdown menu on top of

![Image](https://github.com/sebastianpiresmolin/cinema/assets/128062820/52b56ad3-8c05-4476-9569-8d1866fce6ce)

 About page for the sites:
Frågor och Svar
Kontakta oss
Åldersgränser
Lämna feedback

Check whimsical for design

**_User story:
As a user i want to be able to click on the dropdown menu and see an overlook of the sections of about page that i can go too, to easier find the page that helps me._**

**Comment by Willi86** [comment]
Done, waiting for review to merg
