### ISSUE TITLE
Create footer and style footer element

### ISSUE THREAD

**Issue by MikaelaMathisson** [sebastianpiresmolin/cinema#4]
Create footer for both desktop and mobile.
Style

**_User story:
As a user i want to be able to go to a section from the footer without having to go up to the top again. I want to have an overlook of sections_**

**Comment by MikaelaMathisson** [comment]
I have made a PR:https://github.com/sebastianpiresmolin/cinema/pull/20 
Please check and let me know what you think

**Comment by rasmusbaeckstrom** [comment]
Nice job. This looks good :)

**Comment by Willi86** [comment]
Looks great :)
