### ISSUE TITLE
Create age limit and Q&A page on ABOUT.html

### ISSUE THREAD

**Issue by MikaelaMathisson** [sebastianpiresmolin/cinema#7]
Create pages for the different ones.

**_User Story:
When i click on age limit on menu i want to able to see what age limits there are.
If i click on Q&A pages i want to able to find answers to my questions_**

**Comment by MikaelaMathisson** [comment]
Pull reqest finns här:
https://github.com/sebastianpiresmolin/cinema/pull/8

**Comment by sebastianpiresmolin** [comment]
I have merged this issue. Now ready for testing.
