### ISSUE TITLE
Create header including navbar. Create  navbar including functioning links and styling.

### ISSUE THREAD

**Issue by sebastianpiresmolin** [sebastianpiresmolin/cinema#9]
Navbar includes:

Loggo in the left corner

on mobile, hamburger button is on the left corner also

Menu options:
Biljetter
Nyheter
Filmer och Trailers
Kontakt

Right corner:

"Find us button" (look at whimsical) that navigates to About page (Contact us section)
Search icon with click function(For the person doing filtering)

User stories:

**Navbar**

As a visitor I want to be able to Easily navigate between the different pages on the website so that I can know which movies are available for watching. 

**Find us button**

As a visitor I want to click on this button and be redirected to a map showing exactly where the cinema is located so that I can find where to go when visiting.

**Search Icon**

As a visitor I want to search for titles of movies so that I can learn more about the specific search item. If there is no matching search I want an error message telling me so.

**Comment by MikaelaMathisson** [comment]
I have review this and will be testing it shortly.

**Comment by MikaelaMathisson** [comment]
@sebastianpiresmolin 
I have tested and reviewed.

The navbar has 2 problems. I will put the card back in doing, so you can check it out.

1. The whole navbar disappears if you press the location symbol.  Maybe its just linked to another site, that i have missed?
2. The hamburger menu does not have an hover effect like the rest of the navbar.

**Comment by sebastianpiresmolin** [comment]
@MikaelaMathisson

Thanks for the comment!

The map dot is linking to about.html that is empty at the moment and the hamburger icon doesn't have hover since it's not going to be visible for the mobile users!

Linking this PR to the correct Issue now.
